# Generated by Django 4.2 on 2025-02-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compyuter',
            name='scaner',
            field=models.ManyToManyField(blank=True, related_name='scaner', to='Инвентаризация.scaner', verbose_name='Сканеры'),
        ),
    ]
