# Generated by Django 4.2 on 2025-02-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Texnology',
        ),
    ]
