# Generated by Django 4.2 on 2025-02-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0002_alter_compyuter_scaner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compyuter',
            name='diaganal_monitor',
        ),
        migrations.RemoveField(
            model_name='compyuter',
            name='type_webcamera',
        ),
        migrations.DeleteModel(
            name='MonitorDiaganal',
        ),
        migrations.AddField(
            model_name='compyuter',
            name='type_webcamera',
            field=models.ManyToManyField(blank=True, related_name='typeCamera', to='Инвентаризация.typewebcamera', verbose_name='Тип вебкамера'),
        ),
    ]
