# Generated by Django 4.2 on 2025-02-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Инвентаризация', '0003_remove_compyuter_diaganal_monitor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compyuter',
            name='type_monitor',
        ),
        migrations.AddField(
            model_name='compyuter',
            name='type_monitor',
            field=models.ManyToManyField(blank=True, related_name='typeMonitor', to='Инвентаризация.monitor', verbose_name='Тип Монитора'),
        ),
    ]
